#
# Configuration file for RBMH Technology Blog
#

# Name of the blog (displayed in the header)
name: RBMH Technology

# Short description of blog (displayed in the header)
description: Open Source Center

# URL of Logo of RBMH Technology Blog
logo: /images/RedBullMediaHouse-dark.png

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) if you want to track your visits
google_analytics:

# Your website URL (e.g. http://www.redbullmediahouse.com/
# Used for Sitemap.xml and your RSS feed
# Depending of the URL of RBMH Technology Open Source Blog
url: http://rbmhtechnology.github.io/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Define how many blog entries should be visible on home page
limitPostsOnHomePage: 3

#################################
# Jekyll configuration

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

highlighter: pygments
permalink: /:title/

sass:
  style: compressed # expanded or compressed You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
